### PR TITLE
Create AddElectiveCourses.py file

### PR DESCRIPTION
**Pull request by king9487**

### CODE REVIEW

**Review by king9487 — COMMENTED** [review]
Add get_curriculm(student_id) function

**Review by king9487 — COMMENTED** [review]
Add write_curriculum(student_id, course_id, course_credit, course_time) function

**Review by king9487 — COMMENTED** [review]
change return value

**Review by king9487 — COMMENTED** [review]
Re-update

**Comment by KevinYu0515** [comment]
merge AddElectiveCourses

**Review by king9487 — COMMENTED** [review]
Change the input file from .txt to .json

**Review by king9487 — COMMENTED** [review]
Add search_course(course_id) function

**Review by king9487 — COMMENTED** [review]
Add verify(student_id, course_time), just a idea, not done yet

**Review by king9487 — COMMENTED** [review]
Add new file, Course.json

**Pull request merged**
